# Generated by Django 3.2.4 on 2021-06-17 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_alter_contact_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='twitter_list',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
