# Generated by Django 3.2.4 on 2021-06-20 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_telegrammessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='telegram_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
